version: '3'
services:
  rabbitmqproducerobject:
    build: ./rabbitmqconsumerobject
    network_mode: host
    restart: always



  rabbitmqconsumerobject:
    build: ./rabbitmqproducerobject
    network_mode: host
    restart: always

  rabbitmq:
    image: rabbitmq:3.7.5-management
    hostname: localhost
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq/mnesia/rabbit@app-rabbitmq:cached
    environment:
      RABBITMQ_ERLANG_COOKIE: 6085e2412b6fa88647466c6a81c0cea0
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /